wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.42.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722228310
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 85
      2:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 85
      3:
      - 23
      4: 3.8.19
      5: 0.17.4
      6: 4.42.3
      8:
      - 5
      13: linux-x86_64
